git submodule add git://github.com/tpope/vim-fugitive.git bundle/fugitive
git submodule add git://github.com/mileszs/ack.vim.git bundle/ack
git submodule add git://github.com/vim-scripts/Align.git bundle/align
git submodule add git://github.com/vim-scripts/bufexplorer.zip.git bundle/bufexplorer
git submodule add git://github.com/vim-scripts/camelcasemotion.git bundle/camelcasemotion
git submodule add git://github.com/akitaonrails/Command-T.git bundle/Command-T
git submodule add git://github.com/vim-scripts/CSApprox.git bundle/CSApprox
git submodule add git://github.com/tpope/vim-cucumber.git  bundle/cucumber
git submodule add git://github.com/tpope/vim-endwise.git bundle/endwise
git submodule add git://github.com/tpope/vim-git.git bundle/git
git submodule add git://github.com/tpope/vim-haml.git bundle/haml
git submodule add git://github.com/tpope/vim-markdown.git bundle/markdown
git submodule add git://github.com/vim-scripts/matchit.zip.git bundle/matchit
git submodule add git://github.com/scrooloose/nerdtree.git bundle/NERD_tree
git submodule add git://github.com/scrooloose/nerdcommenter.git bundle/NERD_commenter
git submodule add git://github.com/tpope/vim-pastie.git bundle/pastie
git submodule add git://github.com/tpope/vim-ragtag.git bundle/ragtag
git submodule add git://github.com/tpope/vim-rails.git bundle/rails
git submodule add git://github.com/cakebaker/scss-syntax.vim.git bundle/scss-syntax
git submodule add git://github.com/ciaranm/securemodelines.git bundle/securemodelines
git submodule add git://github.com/honza/snipmate-snippets.git bundle/snipmate-snippets
git submodule add git://github.com/altercation/vim-colors-solarized.git bundle/solarized
git submodule add git://github.com/ervandew/supertab.git bundle/supertab
git submodule add git://github.com/tpope/vim-surround.git bundle/surround
git submodule add git://github.com/scrooloose/syntastic.git bundle/syntastic
git submodule add gits://github.com/vim-scripts/taglist.vim.git bundle/taglist
git submodule add git://github.com/timcharper/textile.vim.git bundle/textile
git submodule add git://github.com/tomtom/tlib_vim.git bundle/tlib_vim
git submodule add git://github.com/MarcWeber/vim-addon-mw-utils.git bundle/vim-addon-mw-utils
git submodule add git://github.com/tpope/vim-unimpaired.git bundle/unimpaired
git submodule add gits://github.com/MarcWeber/vim-addon-mw-utils.git bundle/vim-addon-mw-utils
git submodule add git://github.com/sophacles/vim-bundle-python.git  bundle/vim-bundle-python.git
git submodule add git://github.com/kchmck/vim-coffee-script.git bundle/vim-coffee-script
git submodule add gits://github.com/clones/vim-fuzzyfinder bundle/vim-fuzzyfinder
git submodule add git://github.com/clones/vim-l9.git bundle/l9
git submodule add git://github.com/vim-ruby/vim-ruby.git bundle/vim-ruby
git submodule add git://github.com/garbas/vim-snipmate.git  bundle/vim-snipmate
git submodule add git://github.com/tpope/vim-vividchalk.git bundle/vividchalk
git submodule add git://github.com/hail2u/vim-css3-syntax.git bundle/css3
git submodule add git://github.com/Lokaltog/vim-powerline.git bundle/powerline
git submodule add git://github.com/vim-scripts/FuzzyFinder.git bundle/FuzzyFinder